apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-api
  labels:
    app: currency-api
spec:
  selector:
    matchLabels:
      app: currency-api
  replicas: 1
  template:
    metadata:
      labels:
        app: currency-api
    spec:
      containers:
        - name: currency-api
          image: gcr.io/clever-spirit-402509/kirmayrcosta/currency-api:lastest
          envFrom:
            - configMapRef:
                name: currency-api-configmap
#          volumeMounts:
#            - name: currency-api-configmap
#              mountPath: .env
#              readOnly: true
          ports:
            - containerPort: 3000
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 3000
#            initialDelaySeconds: 10
#            periodSeconds: 3
#          readinessProbe:
#            initialDelaySeconds: 20
#            periodSeconds: 10
#            httpGet:
#              path: /
#              port: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: 300m
            requests:
              memory: 1024Mi
              cpu: 500m
#            volumes:
#              - name: currency-api-configmap
#                mountPath: .env
#                readOnly: true
      imagePullSecrets:
        - name: artifact-registry