apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: currency-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currency-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageValue: 500Mi
          type: AverageValue
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 450
          type: Utilization