apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- hpa.yaml
#- ingress.yaml

configMapGenerator:
- envs:
  - .env
  name: currency-api-configmap
images:
- name: node
  newTag: 8.15.0

