
GET http://localhost:3000
Content-Type: application/json

###

POST http://localhost:3000/v1/currency
Content-Type: application/json

{
"name": "Real",
"alias": "BRL",
"quotes": [
{
  "name": "Dolar",
  "alias": "USD",
  "price": 5.0557
}
]
}


###

POST http://localhost:3000/v1/currency
Content-Type: application/json

{
  "name": "",
  "alias": "",
  "quotes": [
    {
      "alias": "USD",
      "price": 5.0557
    }
  ]
}

###

GET http://localhost:3000/v1/currency
Content-Type: application/json

###

GET http://localhost:3000/v1/currency/BRL
Content-Type: application/json

###

GET http://localhost:3000/v1/currency/converter/BRL/2
Content-Type: application/json

###

PUT http://localhost:3000/v1/currency/BRL
Content-Type: application/json

{
  "name": "Teste de atualizacao",
  "alias": "ABD",
  "quotes": [
    {
      "alias": "USD",
      "price": 5.0557
    }
  ]
}

###
DELETE http://localhost:3000/v1/currency/BRL
Content-Type: application/json


###

POST http://localhost:3000/v1/currency/ABD/quotes
Content-Type: application/json

{
  "alias": "ABC",
  "price": 3.00
}

###
PUT http://localhost:3000/v1/currency/ABD/quotes/ABC
Content-Type: application/json

{
  "alias": "BRL",
  "price": 4.00
}

###

DELETE http://localhost:3000/v1/currency/ABD/quotes/USD