version: '2'

networks:
  loki:
  mongodb_net:
    driver: bridge
    ipam:
      driver: default
      config:
        # Change this subnet range if it conflicts with your personal/work network
        - subnet: 192.168.213.0/24
          gateway: 192.168.213.1
services:
  currency_api:
    container_name: currency_api
    hostname: currency_api
    build:
        context: ../backend
    networks:
      - mongodb_net
      - loki
    ports:
        - 3000:3000
    environment:
      - ENV=DEVELOPMENT
      - SERVICE_NAME=CURRENCY_API
      - MONGODB_URI=mongodb://mongodb:27017/currency
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4317
      - OTEL_METRICS_INTERVAL=5000
      - EXPORTER_LOG_ENDPOINT=http://loki:3100
      - EXPORTER_CACHE_ENDPOINT=redis://redis:6379
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    networks:
      - mongodb_net
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    networks:
      - mongodb_net
    ports:
      - 27017:27017
  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "8889:8889"  # prometheus
    networks:
      - loki
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tmp/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - loki
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboard:/var/lib/grafana/dashboards
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - loki
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    environment:
      - ENDPOINT=otel-collector:4317
    restart: always
    depends_on:
      - otel-collector
    networks:
      - loki
