receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - otlp
    metrics:
      receivers:
        - otlp
      exporters:
        - prometheus
