{
 "title": "Currency API",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "TraceId", "label": "TraceId" }
  ]
 },
 "panels": [
  {
   "title": "Total Requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_responseTime_count{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req Sucesso",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_responseTime_count{job=\"otel-collector\", statusCode=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req Validação",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_responseTime_count{job=\"otel-collector\", statusCode=\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req Erro",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_responseTime_count{job=\"otel-collector\", statusCode=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_responseTime_count{}[5m]))  by (statusCode,path,method))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(http_server_responseTime_bucket{job=\"otel-collector\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}